//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.FirstWebServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FirstWebServiceReference.IFirstWCFWebService")]
    public interface IFirstWCFWebService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFirstWCFWebService/Message", ReplyAction="http://tempuri.org/IFirstWCFWebService/MessageResponse")]
        string Message();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFirstWCFWebService/Message", ReplyAction="http://tempuri.org/IFirstWCFWebService/MessageResponse")]
        System.Threading.Tasks.Task<string> MessageAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFirstWCFWebService/add", ReplyAction="http://tempuri.org/IFirstWCFWebService/addResponse")]
        int add(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFirstWCFWebService/add", ReplyAction="http://tempuri.org/IFirstWCFWebService/addResponse")]
        System.Threading.Tasks.Task<int> addAsync(int x, int y);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFirstWCFWebServiceChannel : Client.FirstWebServiceReference.IFirstWCFWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FirstWCFWebServiceClient : System.ServiceModel.ClientBase<Client.FirstWebServiceReference.IFirstWCFWebService>, Client.FirstWebServiceReference.IFirstWCFWebService {
        
        public FirstWCFWebServiceClient() {
        }
        
        public FirstWCFWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FirstWCFWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FirstWCFWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FirstWCFWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Message() {
            return base.Channel.Message();
        }
        
        public System.Threading.Tasks.Task<string> MessageAsync() {
            return base.Channel.MessageAsync();
        }
        
        public int add(int x, int y) {
            return base.Channel.add(x, y);
        }
        
        public System.Threading.Tasks.Task<int> addAsync(int x, int y) {
            return base.Channel.addAsync(x, y);
        }
    }
}
